# Generated by Django 5.1.4 on 2025-01-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subscription_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vid',
            new_name='img',
        ),
    ]
