# Generated by Django 5.1.4 on 2025-01-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_vid_video_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.ImageField(default='pavan', upload_to='static/zoom'),
            preserve_default=False,
        ),
    ]
