# Generated by Django 5.1.4 on 2025-01-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_video_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='img',
            new_name='img1',
        ),
    ]
