# Generated by Django 5.1.4 on 2025-01-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_img_video_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
